### ISSUE TITLE
Unable to install with pip

### ISSUE THREAD

**Issue by rbignon** [eliteraspberries/python-androidenv#1]
When trying to install with pip, I get this error:

```
Collecting androidenv
  Downloading androidenv-0.6.tar.gz (5.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/rom1/src/beeware/beeware-venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zruj89o2/androidenv_d4f791ac490a4a68a0af34c5482e9bc1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zruj89o2/androidenv_d4f791ac490a4a68a0af34c5482e9bc1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ypzkvn_r
         cwd: /tmp/pip-install-zruj89o2/androidenv_d4f791ac490a4a68a0af34c5482e9bc1/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zruj89o2/androidenv_d4f791ac490a4a68a0af34c5482e9bc1/setup.py", line 3, in <module>
        import androidenv
      File "/tmp/pip-install-zruj89o2/androidenv_d4f791ac490a4a68a0af34c5482e9bc1/androidenv.py", line 39, in <module>
        sdk = os.path.join(home, 'sdk')
      File "/usr/lib/python3.9/posixpath.py", line 76, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This is because, as `setup.py` imports `androidenv`, it requires the environment variables like `ANDROID_HOME`.

**Comment by mansourmoufid** [comment]
Have you set the environment variable [ANDROID_SDK_ROOT](https://developer.android.com/studio/command-line/variables)? If you are using Android Studio, go to Preferences, search "sdk" and copy the path labeled "Android SDK Location". Set ANDROID_SDK_ROOT to this path:

    export ANDROID_SDK_ROOT="/path/to/Android/sdk"

<img width="982" alt="Screen Shot 2021-12-26 at 12 40 25" src="https://user-images.githubusercontent.com/10801249/147416066-cf5164ee-13e8-498d-8fdb-17436bacd8f3.png">

**Comment by rbignon** [comment]
I don't use Android Studio (I use beeware/briefcase). Anyway, when you install a package you may not be in the runtime conditions, so I suggest to avoid importing androidenv in setup.py.

**Comment by mansourmoufid** [comment]
Oh now I understand. I need briefcase to export ANDROID_SDK_ROOT. I'll work on that.
